### ISSUE TITLE
Discontinue Rinkeby subgraphs and deploy to Goerli

### ISSUE THREAD

**Issue by 0xJurassicPunk** [LooksRare/subgraph#81]

**Comment by xhad** [comment]
Looking for help on this?

**Comment by 0xJurassicPunk** [comment]
It should be good but if you have suggestions on how to parametrize YAML files, it would be appreciated! https://github.com/LooksRare/subgraph/issues/57

**Comment by xhad** [comment]
Do you mean for the addresses and block times after you deploy to a local or new chain and dynamically want to inherit those values instead of hard coding them?

**Comment by 0xJurassicPunk** [comment]
Yes! For instance, we keep two copies of the manifest depending on the network at the moment.
Ideally, we should have only one manifest (or a way to compute dynamically) and the address/block references conditional to a config for the networks when it is deployed.

https://github.com/LooksRare/subgraph/tree/master/subgraphs/looks-distribution
https://thegraph.com/docs/en/deploying/deploying-a-subgraph-to-hosted/#deploying-the-subgraph-to-multiple-ethereum-networks
